services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:0.6.43
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=duckduckgo
      - WEBUI_NAME=Lifan's AI Chatbot
      - WEBUI_URL="${WEBUI_URL}"
volumes:
  open-webui:
